# Generated by Django 6.0.1 on 2026-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(max_length=20)),
                ('ocr_draft', models.TextField(help_text='Raw OCR text of the document')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, help_text='Extracted structured data', null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Total wall-clock time in milliseconds', null=True)),
                ('metrics', models.JSONField(blank=True, help_text='Per-step timing and accuracy metrics', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
