# Generated by Django 6.0.1 on 2026-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_alter_extractionjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='viz_data',
            field=models.JSONField(blank=True, help_text='Serialized LangExtract AnnotatedDocument for the visualizer', null=True),
        ),
    ]
